on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.0.0' # default is 'stable'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install NASM
        run: sudo apt-get update && sudo apt-get install -y nasm
      - run: mkdir asm
      - run: nimble build --multimethods:on -Y
      - run: nimble test -Y
